version: "3.9"

services:
  aulas-es-app:
    container_name: aulas-es-container
    image: aulas-es
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./my-data:/app/my-data
    restart: unless-stopped
