name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./web-service-gin

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Instalar dependências
        run: go mod tidy

      - name: Criar diretório de logs
        run: mkdir -p my-data

      - name: Rodar testes
        run: go test ./...

      - name: Build do projeto
        run: go build -o aulasES
