name: Go CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # Permite rodar manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Instalar dependências
      run: go mod tidy
      working-directory: web-service-gin

    - name: Rodar testes
      run: go test ./...
      working-directory: web-service-gin
