name: Deploy Go App via Binary

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build binary
        working-directory: ./web-service-gin
        run: go build -o aulasES

      - name: Copiar binário para o servidor
        uses: appleboy/scp-action@master
        with:
          host: 192.168.0.205
          port: 3022
          username: leo
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "web-service-gin/aulasES"
          target: "/home/leo/aulasES"

      - name: Executar binário no servidor
        uses: appleboy/ssh-action@master
        with:
          host: 192.168.0.205
          port: 3022
          username: leo
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            pkill aulasES || true
            cd /home/leo/aulasES
            nohup ./aulasES > output.log 2>&1 &
