name: Deploy Go App

on:
  push:
    branches:
      - main  # Or your production branch, e.g., main or master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"  # Use the Go version your project requires

      - name: Build
        run: go build -o myapp

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}  # Replace with your server IP/hostname
          username: ${{ secrets.SERVER_USER }}  # Replace with your server username
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Replace with your SSH private key
          source: "myapp"  # Only send the binary
          target: "/home/your_user/app"  # Replace with your server directory

      - name: Run on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            /home/your_user/app/myapp  # Execute the app on the server
