name: Deploy Go App via Binary

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build binary
        working-directory: ./web-service-gin
        run: go build -o aulasES

      - name: Copiar binário para o servidor
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 3022
          source: "web-service-gin/aulasES"
          target: "C:/Users/${{ secrets.SERVER_USER }}/deploy-aulasES"

      - name: Executar binário no servidor
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 3022
          script: |
            taskkill /F /IM aulasES.exe || echo "Processo não encontrado"
            cd C:/Users/${{ secrets.SERVER_USER }}/deploy-aulasES
            ./aulasES.exe
