name: Deploy Go Binary to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build Go binary
        working-directory: ./web-service-gin
        run: go build -o aulasES

      - name: Copy binary to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "web-service-gin/aulasES"
          target: "/home/${{ secrets.SERVER_USER }}/deploy-aulasES"

      - name: Run Go binary on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            pkill aulasES || echo "No process found"
            cd /home/${{ secrets.SERVER_USER }}/deploy-aulasES
            chmod +x aulasES
            nohup ./aulasES > output.log 2>&1 &
