name: Deploy Go App via Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t aulas-es-app ./web-service-gin

      - name: Enviar imagem Docker para servidor
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./web-service-gin/docker-compose.yml"
          target: "/home/${{ secrets.SERVER_USER }}/aulasES"

      - name: Enviar Dockerfile
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./web-service-gin/dockerfile"
          target: "/home/${{ secrets.SERVER_USER }}/aulasES"

      - name: Deploy no servidor
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/aulasES
            docker-compose down
            docker-compose up -d --build
